### PR TITLE
Use px instead of em in media queries

### LINKED ISSUE #78: Months and days overlapping due to "em" units
### Description
Using "px" instead of "em" will fix the months and days overlapping in the 852 x 621 resolution when setting the "body" font-size to 18px. I understand the usage of "em", but I think we would be safer just using px for the media queries.

Please see the bug below:
screen shot 2018-06-19 at 18 03 51

@krystalcampioni, may I proceed and submit a PR for this?

### Code sample 
[ If you are submitting a bug issue, paste your code so I can reproduce it, or a link to a Codepen with it ]

### Steps to Reproduce

1. Set the body font-size to 18px
2. Open date picker in this resolution: 852 x 621
3. The month and day labels are overlapping

**Expected behavior:** [What you expected to happen]
The month and day labels shouldn't be overlapping.

**Actual behavior:** [What actually happened]
The month and day labels are overlapping.

### Datepicker Version
2.2.4
[ The version of the datepicker you have installed in your project ]

### PR DESCRIPTION
**Pull request by SnitramDev**
This fixes #78.

### CODE REVIEW

File: src/components/DatePicker.vue [hunk 1]
```diff
@@ -256,15 +256,15 @@ export default {
     ...Helpers,
 
     handleWindowResize() {
-      let screenSizeInEm = window.innerWidth / parseFloat(getComputedStyle(document.querySelector('body'))['font-size']);
+      // let screenSizeInEm = window.innerWidth / parseFloat(getComputedStyle(document.querySelector('body'))['font-size']);
```
Comment (krystalcampioni) [inline src/components/DatePicker.vue]: we should probably remove this comment if we wont use the em calculation anymore :)

Comment (SnitramDev) [reply src/components/DatePicker.vue]: Oops! Thanks!
